"""Installer contract tests use only disposable directories."""

from __future__ import annotations

import importlib.util
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest
from unittest import mock


SCRIPT = Path(__file__).resolve().parents[1] / "scripts" / "install_skills.py"
SPEC = importlib.util.spec_from_file_location("install_skills", SCRIPT)
installer = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(installer)


def make_collection(repo: Path) -> None:
    for name in installer.SKILL_NAMES:
        skill = repo / "skills" / name
        (skill / "references").mkdir(parents=True)
        (skill / "scripts").mkdir()
        (skill / "agents").mkdir()
        (skill / "SKILL.md").write_text(f"---\nname: {name}\ndescription: Sample\n---\n", encoding="utf-8")
        (skill / "references" / "tiếng Việt.md").write_text("Nội dung mẫu", encoding="utf-8")
        (skill / "scripts" / "inspect.py").write_text("print('sample')\n", encoding="utf-8")
        (skill / "agents" / "openai.yaml").write_text("interface:\n  display_name: Sample\n", encoding="utf-8")


class InstallerTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory(prefix="superpowerpoint-install-")
        self.addCleanup(self.temporary.cleanup)
        self.base = Path(self.temporary.name)
        self.repo = self.base / "nguồn kỹ năng"
        self.destination = self.base / "đích có dấu" / "skills"
        make_collection(self.repo)

    def test_copies_complete_collection_and_nested_resources_to_unicode_path(self) -> None:
        targets = installer.install_skills(self.repo, self.destination)
        self.assertEqual(set(path.name for path in targets), set(installer.SKILL_NAMES))
        for name in installer.SKILL_NAMES:
            source = self.repo / "skills" / name
            target = self.destination / name
            source_files = {path.relative_to(source): path.read_bytes() for path in source.rglob("*") if path.is_file()}
            target_files = {path.relative_to(target): path.read_bytes() for path in target.rglob("*") if path.is_file()}
            self.assertEqual(target_files, source_files)

    def test_dry_run_does_not_create_destination(self) -> None:
        targets = installer.install_skills(self.repo, self.destination, dry_run=True)
        self.assertEqual(len(targets), 6)
        self.assertFalse(self.destination.parent.exists())

    def test_does_not_distribute_generated_python_caches(self) -> None:
        source = self.repo / "skills" / "reviewing-powerpoint" / "scripts"
        cache = source / "__pycache__"
        cache.mkdir()
        (cache / "inspect.cpython-313.pyc").write_bytes(b"generated bytecode")
        (source / "legacy.pyc").write_bytes(b"generated bytecode")
        installer.install_skills(self.repo, self.destination)
        installed = self.destination / "reviewing-powerpoint" / "scripts"
        self.assertTrue((installed / "inspect.py").is_file())
        self.assertFalse((installed / "__pycache__").exists())
        self.assertFalse((installed / "legacy.pyc").exists())

    def test_last_target_conflict_prevents_all_writes(self) -> None:
        conflict = self.destination / installer.SKILL_NAMES[-1]
        conflict.mkdir(parents=True)
        sentinel = conflict / "existing.txt"
        sentinel.write_bytes(b"must remain unchanged")
        with self.assertRaises(installer.InstallError):
            installer.install_skills(self.repo, self.destination)
        self.assertEqual(list(self.destination.iterdir()), [conflict])
        self.assertEqual(sentinel.read_bytes(), b"must remain unchanged")

    def test_existing_file_target_is_refused(self) -> None:
        self.destination.mkdir(parents=True)
        conflict = self.destination / installer.SKILL_NAMES[2]
        conflict.write_bytes(b"existing file")
        with self.assertRaises(installer.InstallError):
            installer.install_skills(self.repo, self.destination)
        self.assertEqual(conflict.read_bytes(), b"existing file")
        self.assertEqual(len(list(self.destination.iterdir())), 1)

    def test_dangling_symlink_target_is_refused(self) -> None:
        self.destination.mkdir(parents=True)
        conflict = self.destination / installer.SKILL_NAMES[-1]
        try:
            conflict.symlink_to(self.base / "not-created", target_is_directory=True)
        except (OSError, NotImplementedError) as exc:
            self.skipTest(f"Symbolic links unavailable in this environment: {exc}")
        with self.assertRaises(installer.InstallError):
            installer.install_skills(self.repo, self.destination)
        self.assertTrue(conflict.is_symlink())
        self.assertEqual(list(self.destination.iterdir()), [conflict])

    def test_incomplete_source_collection_cannot_partially_install(self) -> None:
        (self.repo / "skills" / installer.SKILL_NAMES[-1] / "SKILL.md").unlink()
        with self.assertRaises(installer.InstallError):
            installer.install_skills(self.repo, self.destination)
        self.assertFalse(self.destination.exists())

    def test_destination_file_is_preserved(self) -> None:
        self.destination.parent.mkdir(parents=True)
        self.destination.write_bytes(b"not a directory")
        with self.assertRaises(installer.InstallError):
            installer.install_skills(self.repo, self.destination)
        self.assertEqual(self.destination.read_bytes(), b"not a directory")

    def test_source_tree_destination_is_refused(self) -> None:
        with self.assertRaises(installer.InstallError):
            installer.install_skills(self.repo, self.repo / "skills" / "nested")
        self.assertFalse((self.repo / "skills" / "nested").exists())

    def test_copy_failure_removes_only_new_skill_directories(self) -> None:
        self.destination.mkdir(parents=True)
        unrelated = self.destination / "other-skill"
        unrelated.mkdir()
        (unrelated / "saved.txt").write_bytes(b"preserve me")
        with mock.patch.object(installer.shutil, "copytree", side_effect=OSError("simulated disk failure")):
            with self.assertRaises(installer.InstallError):
                installer.install_skills(self.repo, self.destination)
        self.assertEqual(list(self.destination.iterdir()), [unrelated])
        self.assertEqual((unrelated / "saved.txt").read_bytes(), b"preserve me")

    def test_cli_requires_an_explicit_destination(self) -> None:
        result = subprocess.run([sys.executable, str(SCRIPT)], capture_output=True, text=True)
        self.assertEqual(result.returncode, 2)
        self.assertIn("--dest", result.stderr)


if __name__ == "__main__":
    unittest.main()
